# Generated by Django 3.1.7 on 2021-03-06 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210304_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='djangodbmodelsfieldscharfield', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 14, 24, 30, 85242)),
        ),
    ]
