# Generated by Django 3.1.7 on 2021-03-02 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210302_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 15, 18, 31, 41281)),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='hi', editable=False, max_length=100, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
